<a href="https://colab.research.google.com/github/NEEEEEEEEEEEL/Debnil/blob/main/spam_email_detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [5]:
df=pd.read_csv("spam.csv")
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [9]:
df.Category.value_counts()  #counts the diff types of category

Category
ham     4825
spam     747
Name: count, dtype: int64

In [14]:
df["spam"]=df['Category'].apply(lambda x:1 if x=="spam" else 0)
df['spam']

0       0
1       0
2       1
3       0
4       0
       ..
5567    1
5568    0
5569    0
5570    0
5571    0
Name: spam, Length: 5572, dtype: int64

or you can write the same thing

In [19]:
#this is easy
def spam_num(x):
  if x=="spam":
    return 1
  return 0

df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [32]:
df.shape  #before splitting

(5572, 3)

In [81]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df.Message	,df.spam,test_size=0.2)

In [82]:
x_train.shape

(4457,)

In [83]:
x_test.shape

(1115,)

In [84]:
x_train[:4] #prints first 4 samples

2441    Great. I'm in church now, will holla when i ge...
4948    Great News! Call FREEFONE 08006344447 to claim...
4310    He dint tell anything. He is angry on me that ...
1473    Just sent you an email – to an address with in...
Name: Message, dtype: object

In [85]:
y_train[:4]

2441    0
4948    1
4310    0
1473    0
Name: spam, dtype: int64

In [47]:
type(x_train.values)

numpy.ndarray

In [59]:
print(type(x_train_array))

<class 'str'>


In [86]:
from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer()
x_train_cv = v.fit_transform(x_train.values)
x_train_cv

<4457x7725 sparse matrix of type '<class 'numpy.int64'>'
	with 59132 stored elements in Compressed Sparse Row format>

In [87]:
x_train_cv.toarray()[:2][0]
x_train_cv.shape

(4457, 7725)

In [88]:
v.get_feature_names_out()[10:30]

array(['021', '03', '04', '0430', '05', '050703', '0578', '06', '07',
       '07008009200', '07046744435', '07090201529', '07090298926',
       '07099833605', '07123456789', '0721072', '07732584351',
       '07734396839', '07742676969', '07753741225'], dtype=object)

In [89]:
v.vocabulary_

{'great': 3249,
 'in': 3643,
 'church': 1840,
 'now': 4853,
 'will': 7503,
 'holla': 3479,
 'when': 7465,
 'get': 3141,
 'out': 5018,
 'news': 4768,
 'call': 1632,
 'freefone': 3008,
 '08006344447': 57,
 'to': 6918,
 'claim': 1847,
 'your': 7694,
 'guaranteed': 3277,
 '1000': 260,
 'cash': 1702,
 'or': 4985,
 '2000': 355,
 'gift': 3152,
 'speak': 6348,
 'live': 4161,
 'operator': 4972,
 'he': 3374,
 'dint': 2352,
 'tell': 6737,
 'anything': 1021,
 'is': 3747,
 'angry': 984,
 'on': 4946,
 'me': 4407,
 'that': 6792,
 'why': 7486,
 'you': 7690,
 'told': 6935,
 'abi': 768,
 'just': 3878,
 'sent': 6013,
 'an': 974,
 'email': 2595,
 'address': 831,
 'with': 7531,
 'incomm': 3653,
 'it': 3759,
 'right': 5783,
 'ah': 886,
 'see': 5980,
 'have': 3364,
 'be': 1295,
 'the': 6796,
 'lingo': 4137,
 'let': 4091,
 'know': 3960,
 'wot': 7593,
 'earth': 2532,
 'has': 3353,
 'finished': 2883,
 'making': 4337,
 'hey': 3428,
 'don': 2431,
 'forget': 2970,
 'are': 1069,
 'mine': 4489,
 'for': 2962,
 'my': 

In [90]:
x_train_np=x_train_cv.toarray()
x_train_np[:4]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [96]:
from sklearn.naive_bayes import  MultinomialNB

model=MultinomialNB()
model.fit(x_train_cv,y_train)

MultinomialNB()

In [103]:
x_test_cv=v.transform(x_test)
y_predicted=model.predict(x_test_cv)
y_predicted

array([0, 0, 0, ..., 1, 0, 0])

testing

In [104]:
emails=[
    'hey neel,please hire me as your employee',
    'urgent 20% discount on shopping,dont miss it'
]
email_count=v.transform(emails)
model.predict(email_count)
#the o/p says that the first one is not spam but the second one is

array([0, 1])

###you can just do all these by simply:

In [78]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline
clf=Pipeline([
    ('vectorizer',CountVectorizer()),
    ('nb',MultinomialNB())
])

In [105]:
clf.fit(x_train,y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [107]:
clf.predict(x_test)

array([0, 0, 0, ..., 1, 0, 0])

In [110]:
emails=[
    'hey neel,please hire me as your employee',
    'urgent 20% discount on shopping,dont miss it',
    'HURRY you are missing on a job offer',
    '90LPA job,click to register'
]
clf.predict(emails)

array([0, 1, 0, 0])